root: ???

datasets:
  data: ${root}/data
  processed: ${root}/processed_data
  selected: ${.data}
  partitioned: ${.processed}/partitioned
  test: ${.selected}/test
  julia: ${.selected}/Data_Julia
  sao: ${.selected}/Completed_SAO_V3.hdf5

training:
  device: cuda
  epochs: 1
  logger: "trainer"

years:
  start: 2002
  end: 2021

hpo:
  ntrials: 10
  logger: "optuna"
  min_lr: 1e-6
  max_lr: 1e-1
  min_nlayers: 2
  max_nlayers: 20
  min_nunits: 4
  max_nunits: 128
  min_dropout: 0.05
  max_dropout: 0.5

action: create_partition
