root: ???

study_name: first_julia_nn

datasets:
  data: ${root}/data
  processed: ${root}/processed_data
  selected: ${.data}
  partitioned: ${.processed}/partitioned
  test: ${.selected}/test
  julia: ${.selected}/Data_Julia
  sao: ${.selected}/Completed_SAO_V3.hdf5
  predictions: ${.processed}/nn_predictions.csv
  confusion: ${.processed}/nn_evaluation_confusion.csv
  nn_inputs: ${.processed}/nn_evaluation_inputs.csv

geomagneticindices:
  UTC_offset: -5
  Kp_ap_Ap_SN_F107:
    host: ftp.gfz-potsdam.de
    path: /pub/home/obs/Kp_ap_Ap_SN_F107
  hF:
    host: ftp.ngdc.noaa.gov
    path: /ionosonde
    station: JI91J
    obs_times: # UTC
      - "0000"
      - "0015"
      - "0030"
    year_mapping:
      2022: mids_2022/${..station}/individual/2022
      2021: mids13/${..station}/individual/2021
      2020: mids12/${..station}/individual/2020


training:
  device: cuda
  epochs: 30
  logger: trainer
  patience: 5

years:
  start: 2002
  end: 2021

hpo:
  ntrials: 1000
  logger: study
  min_lr: 1e-6
  max_lr: 1e-2
  min_nlayers: 2
  max_nlayers: 10
  min_nunits: 4
  max_nunits: 64
  min_dropout: 0.05
  max_dropout: 0.5
  rdb: mysql+pymysql://userr2232@127.0.0.1/first_julia_nn
  plot: HPO.html

model:
  path: ${root}/models
  nn_checkpoint: ${study_name}.pt
  scaler_checkpoint: scaler.gz
  nfeatures: 8
  ntargets: 1
  features:
    - V_hF
    - V_hF_prev
    - F10.7
    - F10.7 (90d)
    - AP
    - AP (24h)
    - DNS
    - DNC


final:
  split:
    train: 70
    valid: 20
  logger: final

action: create_partition

inference:
  start: ???
  end: ???