root: ???

study_name: 2hour_delay

datasets:
  data: ${root}/data
  processed: ${root}/processed_data
  selected: ${.data}
  partitioned: ${.processed}/partitioned # /Users/userr2232/Documents/misc/first-julia-nn/processed_data/partitioned
  test: ${.selected}/test
  julia: ${.selected}/Data_Julia
  sao: ${.selected}/Completed_SAO_V3.hdf5
  predictions: ${.processed}/nn_predictions.csv
  confusion: ${.processed}/nn_evaluation_confusion.csv
  nn_inputs: ${.processed}/nn_evaluation_inputs.csv

preprocessing:
  delta_hours: 2

cross_validation:
  mode: sliding_window
  training_window_length: 2
  validation_window_length: 1

geomagneticindices:
  UTC_offset: -5
  Kp_ap_Ap_SN_F107:
    host: ftp.gfz-potsdam.de
    path: /pub/home/obs/Kp_ap_Ap_SN_F107
  hF:
    host: ftp.ngdc.noaa.gov # NOAA server
    path: /ionosonde
    station: JI91J # Jicamarca station
    obs_times: # UTC
      - "0000" # 1900 LT
      - "0015" # 1915 LT
      - "0030" # 1930 LT
    year_mapping:
      2022: mids_2022/${..station}/individual/2022
      2021: mids13/${..station}/individual/2021
      2020: mids12/${..station}/individual/2020 # TODO: create year mapping for 2023

training:
  device: cuda
  epochs: 40
  logger: trainer
  patience: 10

years:
  start: 2002
  end: 2019

hpo:
  ntrials: 1000
  logger: study
  min_lr: 1e-4
  max_lr: 1e-3
  min_nlayers: 5
  max_nlayers: 10
  min_nunits: 4
  max_nunits: 128
  min_dropout: 0.01
  max_dropout: 0.1
  rdb: mysql+pymysql://userr2232@127.0.0.1/first_julia_nn
  plot: HPO.html

model:
  path: ${root}/models
  nn_checkpoint: ${study_name}.pt
  scaler_checkpoint: scaler.gz
  ntargets: 1
  kwargs:
    batch_size: 16
  features:
    - foF2
    - V_hF
    - V_hF_prev
    - delta_hF_div_delta_time
    - F10.7
    - F10.7 (90d dev.)
    - AP
    - AP (24h)
    - DNS
    - DNC

final:
  split:
    train: 70
    valid: 20
  logger: final

action: ???

inference:
  start: ???
  end: ???

explanation:
  sample_size: 300
